#include <functional>
#include <memory>
#include <algorithm>
#include <iostream>
#include <sstream>
#include <list>
#include <optional>
#include <filesystem>
#include <unordered_map>
#include <unordered_set>
#include <map>
#include <set>
#include <glm/glm.hpp>
#include <valarray>
